### ISSUE TITLE
Support for OpenSCAD modules

### ISSUE THREAD

**Issue by nyaray** [farrellm/scad-clj#34]
So, I noticed that support for modules was removed in 29a5988806643351f98dbe2e6ef24b9029a85874 without any explanation and was curious why that was done. Wouldn't it be useful for interop with existing utilities/packages that people are sharing?

**Comment by farrellm** [comment]
That was a very long time ago ... as you can see, it predates some major architectural changes. I don't remember, but I think I added those because I was trying to make scad-clj generate OpenSCAD functions, which I later dropped in favor of using Clojure functions to generate unstructured OpenSCAD code.

I am not opposed to adding features to support interop with existing utilities/packages that people are sharing. Importing and calling user functions should be straightforward to add. Exporting functions would require more contemplation.

**Comment by farrellm** [comment]
#36 deployed in version 0.5.3
I'm going to mark this issue closed. Please open a new issue if any problems arise or if you have ideas for changes or improvements to the module implementation.
